# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bab', models.CharField(choices=[('0', 'slow'), ('1', 'medium'), ('2', 'fast')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelCount', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('levelClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Class')),
            ],
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('intellect', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='base_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.StatBlock'),
        ),
    ]
