# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_choicetype_outstandingchoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutstandingChoices',
            new_name='OutstandingChoice',
        ),
    ]
