# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_spell_spellknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellknown',
            name='location',
            field=models.CharField(choices=[('0', 'mind'), ('1', 'spell_book')], default='0', max_length=1),
        ),
    ]
