# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_spellknown_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellknown',
            name='learnedClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characters.Class'),
        ),
    ]
