# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_spellknown_learnedclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='fieldType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.FieldType'),
        ),
    ]
