# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20170915_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='unknown', max_length=255)),
                ('outcome', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('choiceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='characters.ChoiceType')),
            ],
        ),
        migrations.RemoveField(
            model_name='outstandingchoice',
            name='character',
        ),
        migrations.RemoveField(
            model_name='outstandingchoice',
            name='choiceType',
        ),
        migrations.DeleteModel(
            name='OutstandingChoice',
        ),
    ]
