# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20170918_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='casterType',
            field=models.CharField(choices=[('0', 'none'), ('1', 'weak'), ('2', 'strong')], default='0', max_length=1),
        ),
    ]
