# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_class_playstyletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hd',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='class',
            name='skillPointsPerLevel',
            field=models.IntegerField(default=2),
        ),
    ]
