# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_class_classskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trait', models.CharField(max_length=200)),
                ('size', models.IntegerField(choices=[(-4, 'fine'), (-3, 'diminutive'), (-2, 'tiny'), (-1, 'small'), (0, 'medium'), (1, 'large'), (2, 'huge'), (3, 'gargantuan'), (4, 'collosal')], default=0)),
                ('height', models.IntegerField(choices=[('0', 'puny'), ('1', 'short'), ('2', 'average'), ('3', 'tall'), ('4', 'towering')], default='2')),
                ('weight', models.IntegerField(choices=[('0', 'frail'), ('1', 'thin'), ('2', 'average'), ('3', 'built'), ('4', 'heavy')], default='2')),
                ('ageScale', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
    ]
