# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='height',
            field=models.IntegerField(choices=[(0, 'puny'), (1, 'short'), (2, 'average'), (3, 'tall'), (4, 'towering')], default=2),
        ),
        migrations.AlterField(
            model_name='race',
            name='weight',
            field=models.IntegerField(choices=[(0, 'frail'), (1, 'thin'), (2, 'average'), (3, 'built'), (4, 'heavy')], default=2),
        ),
    ]
