# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20170918_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='isThrown',
            field=models.IntegerField(choices=[(0, 'not thrown'), (1, 'thrown')], default=0),
        ),
    ]
