# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_auto_20170918_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='castingTime',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='shortDescription',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
