# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_auto_20170918_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='defaultValue',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
