# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_field_defaultvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='spellsKnown',
            field=models.CharField(choices=[('0', 'knows-all'), ('1', 'selected'), ('2', 'selected-can-copy')], default='0', max_length=1),
        ),
    ]
