# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_auto_20170922_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fieldValues',
            field=models.CharField(default='{}', max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
