# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_auto_20170922_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fieldValues',
            field=models.TextField(default='{}'),
        ),
    ]
